---

- name: Install Mapcrafter requirements
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - cmake
    - imagemagick
    - libboost-filesystem-dev
    - libboost-iostreams-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libjpeg-dev
    - libpng-dev

- name: Clone Mapcrafter
  sudo: yes
  git:
    repo: https://github.com/mapcrafter/mapcrafter.git
    dest: /usr/local/src/mapcrafter
    clone: yes
    recursive: yes

- name: Build & Install Mapcrafter
  with_items:
    - cmake .
    - make
    - make install
    - ldconfig
  shell: "{{ item }}"
  args:
    chdir: /usr/local/src/mapcrafter

- name: Extract Minecraft textures
  sudo: yes
  shell: /usr/local/src/mapcrafter/src/tools/mapcrafter_textures.py "/home/{{ minecraft_user }}/minecraft_client.1.12.jar" "/usr/local/share/mapcrafter/textures"

- name: Install Mapcrafter cron script
  template:
    src: etc/cron.daily/mapcrafter.j2
    dest: /etc/cron.daily/mapcrafter
    mode: 0755

- name: Install Mapcrafter config file
  template:
    src: etc/mapcrafter.conf.j2
    dest: /etc/mapcrafter.conf
    mode: 0644

- name: Install Mapcrafter Apache config file
  template:
    src: etc/apache2/sites-available/mapcrafter.conf.j2
    dest: /etc/apache2/sites-available/mapcrafter.conf
    mode: 0644

- name: Enable Mapcrafter site
  shell: "a2ensite mapcrafter"
  notify: "Restart Apache"
